// Projekt:      SmartQuartier DataService
// Firma:        ABB Technikerschule
// Autor:        Marco Bontognali
//
// Beschreibung: Konfiguration des SmartQuartier DataService
//               - DataService.conf wird im aktuellen Directory gesucht
//               - Zeilen beginnend mit // werden nicht gelesen
//               - Starten mit Kommandozeile: java -jar SmartQuartierDataService.jar

// Der DataService liest regelmässig Messwerte der SmartHomes
// Hier wird die Zykluszeit eingestellt
POLL_CYCLE_SECONDS = 30

// SmartHomes registrieren sich beim DataService auf diesem Port
// Events von SmartHomes werden ebenfalls an diesen Port gesendet
REGISTER_PORT = 11000

// ServiceProvider fragen auf diesem Port History, Statistic und Forecast an
REQUEST_PORT = 11001

// Der DataService schreibt Messwerte und Ereignisse entweder in csv-Files oder in eine Datenbank
PERSISTENCE = File
//PERSISTENCE = Database
