//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    getSmartQuartierHistory(): Promise<SmartQuartierHistoryResponse> {
        let url_ = this.baseUrl + "/smart-quartier/history";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSmartQuartierHistory(_response);
        });
    }

    protected processGetSmartQuartierHistory(response: Response): Promise<SmartQuartierHistoryResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SmartQuartierHistoryResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SmartQuartierHistoryResponse>(null as any);
    }

    getSmartQuartierStatistic(): Promise<SmartQuartierStatisticResponse> {
        let url_ = this.baseUrl + "/smart-quartier/statistic";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSmartQuartierStatistic(_response);
        });
    }

    protected processGetSmartQuartierStatistic(response: Response): Promise<SmartQuartierStatisticResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SmartQuartierStatisticResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SmartQuartierStatisticResponse>(null as any);
    }

    getAbout(): Promise<VersionInfo> {
        let url_ = this.baseUrl + "/about";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAbout(_response);
        });
    }

    protected processGetAbout(response: Response): Promise<VersionInfo> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = VersionInfo.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VersionInfo>(null as any);
    }
}

export class SmartQuartierHistoryResponse implements ISmartQuartierHistoryResponse {
    measurements?: SmartQuartierMeasurement[];
    events?: SmartQuartierEvent[];

    constructor(data?: ISmartQuartierHistoryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["measurements"])) {
                this.measurements = [] as any;
                for (let item of _data["measurements"])
                    this.measurements!.push(SmartQuartierMeasurement.fromJS(item));
            }
            if (Array.isArray(_data["events"])) {
                this.events = [] as any;
                for (let item of _data["events"])
                    this.events!.push(SmartQuartierEvent.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SmartQuartierHistoryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierHistoryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.measurements)) {
            data["measurements"] = [];
            for (let item of this.measurements)
                data["measurements"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.events)) {
            data["events"] = [];
            for (let item of this.events)
                data["events"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISmartQuartierHistoryResponse {
    measurements?: SmartQuartierMeasurement[];
    events?: SmartQuartierEvent[];
}

export class SmartQuartierMeasurement implements ISmartQuartierMeasurement {
    timeStamp?: Date;
    buildingID?: string;
    brightness?: number;
    temperature?: number;
    humidity?: number;
    gas?: number;

    constructor(data?: ISmartQuartierMeasurement) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timeStamp = _data["timeStamp"] ? new Date(_data["timeStamp"].toString()) : undefined as any;
            this.buildingID = _data["buildingID"];
            this.brightness = _data["brightness"];
            this.temperature = _data["temperature"];
            this.humidity = _data["humidity"];
            this.gas = _data["gas"];
        }
    }

    static fromJS(data: any): SmartQuartierMeasurement {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierMeasurement();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timeStamp"] = this.timeStamp ? this.timeStamp.toISOString() : undefined as any;
        data["buildingID"] = this.buildingID;
        data["brightness"] = this.brightness;
        data["temperature"] = this.temperature;
        data["humidity"] = this.humidity;
        data["gas"] = this.gas;
        return data;
    }
}

export interface ISmartQuartierMeasurement {
    timeStamp?: Date;
    buildingID?: string;
    brightness?: number;
    temperature?: number;
    humidity?: number;
    gas?: number;
}

export class SmartQuartierEvent implements ISmartQuartierEvent {
    timeStamp?: Date;
    buildingID?: string;
    type?: string;
    data?: string;

    constructor(data?: ISmartQuartierEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timeStamp = _data["timeStamp"] ? new Date(_data["timeStamp"].toString()) : undefined as any;
            this.buildingID = _data["buildingID"];
            this.type = _data["type"];
            this.data = _data["data"];
        }
    }

    static fromJS(data: any): SmartQuartierEvent {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timeStamp"] = this.timeStamp ? this.timeStamp.toISOString() : undefined as any;
        data["buildingID"] = this.buildingID;
        data["type"] = this.type;
        data["data"] = this.data;
        return data;
    }
}

export interface ISmartQuartierEvent {
    timeStamp?: Date;
    buildingID?: string;
    type?: string;
    data?: string;
}

export class SmartQuartierStatisticResponse implements ISmartQuartierStatisticResponse {
    measurements?: SmartQuartierMeasurementStatistic;
    events?: SmartQuartierEventStatistic;

    constructor(data?: ISmartQuartierStatisticResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.measurements = _data["measurements"] ? SmartQuartierMeasurementStatistic.fromJS(_data["measurements"]) : undefined as any;
            this.events = _data["events"] ? SmartQuartierEventStatistic.fromJS(_data["events"]) : undefined as any;
        }
    }

    static fromJS(data: any): SmartQuartierStatisticResponse {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierStatisticResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["measurements"] = this.measurements ? this.measurements.toJSON() : undefined as any;
        data["events"] = this.events ? this.events.toJSON() : undefined as any;
        return data;
    }
}

export interface ISmartQuartierStatisticResponse {
    measurements?: SmartQuartierMeasurementStatistic;
    events?: SmartQuartierEventStatistic;
}

export class SmartQuartierMeasurementStatistic implements ISmartQuartierMeasurementStatistic {
    brightness?: SmartQuartierNumericStatistic;
    temperature?: SmartQuartierNumericStatistic;
    humidity?: SmartQuartierNumericStatistic;
    gas?: SmartQuartierNumericStatistic;

    constructor(data?: ISmartQuartierMeasurementStatistic) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.brightness = _data["brightness"] ? SmartQuartierNumericStatistic.fromJS(_data["brightness"]) : undefined as any;
            this.temperature = _data["temperature"] ? SmartQuartierNumericStatistic.fromJS(_data["temperature"]) : undefined as any;
            this.humidity = _data["humidity"] ? SmartQuartierNumericStatistic.fromJS(_data["humidity"]) : undefined as any;
            this.gas = _data["gas"] ? SmartQuartierNumericStatistic.fromJS(_data["gas"]) : undefined as any;
        }
    }

    static fromJS(data: any): SmartQuartierMeasurementStatistic {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierMeasurementStatistic();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["brightness"] = this.brightness ? this.brightness.toJSON() : undefined as any;
        data["temperature"] = this.temperature ? this.temperature.toJSON() : undefined as any;
        data["humidity"] = this.humidity ? this.humidity.toJSON() : undefined as any;
        data["gas"] = this.gas ? this.gas.toJSON() : undefined as any;
        return data;
    }
}

export interface ISmartQuartierMeasurementStatistic {
    brightness?: SmartQuartierNumericStatistic;
    temperature?: SmartQuartierNumericStatistic;
    humidity?: SmartQuartierNumericStatistic;
    gas?: SmartQuartierNumericStatistic;
}

export class SmartQuartierNumericStatistic implements ISmartQuartierNumericStatistic {
    min?: SmartQuartierStatisticSample;
    max?: SmartQuartierStatisticSample;
    average?: number;

    constructor(data?: ISmartQuartierNumericStatistic) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.min = _data["min"] ? SmartQuartierStatisticSample.fromJS(_data["min"]) : undefined as any;
            this.max = _data["max"] ? SmartQuartierStatisticSample.fromJS(_data["max"]) : undefined as any;
            this.average = _data["average"];
        }
    }

    static fromJS(data: any): SmartQuartierNumericStatistic {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierNumericStatistic();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["min"] = this.min ? this.min.toJSON() : undefined as any;
        data["max"] = this.max ? this.max.toJSON() : undefined as any;
        data["average"] = this.average;
        return data;
    }
}

export interface ISmartQuartierNumericStatistic {
    min?: SmartQuartierStatisticSample;
    max?: SmartQuartierStatisticSample;
    average?: number;
}

export class SmartQuartierStatisticSample implements ISmartQuartierStatisticSample {
    timeStamp?: Date;
    buildingID?: string;
    value?: number;

    constructor(data?: ISmartQuartierStatisticSample) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timeStamp = _data["timeStamp"] ? new Date(_data["timeStamp"].toString()) : undefined as any;
            this.buildingID = _data["buildingID"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): SmartQuartierStatisticSample {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierStatisticSample();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timeStamp"] = this.timeStamp ? this.timeStamp.toISOString() : undefined as any;
        data["buildingID"] = this.buildingID;
        data["value"] = this.value;
        return data;
    }
}

export interface ISmartQuartierStatisticSample {
    timeStamp?: Date;
    buildingID?: string;
    value?: number;
}

export class SmartQuartierEventStatistic implements ISmartQuartierEventStatistic {
    gas?: number;
    fire?: number;
    motion?: number;
    sound?: number;
    rfid?: number;

    constructor(data?: ISmartQuartierEventStatistic) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.gas = _data["gas"];
            this.fire = _data["fire"];
            this.motion = _data["motion"];
            this.sound = _data["sound"];
            this.rfid = _data["rfid"];
        }
    }

    static fromJS(data: any): SmartQuartierEventStatistic {
        data = typeof data === 'object' ? data : {};
        let result = new SmartQuartierEventStatistic();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["gas"] = this.gas;
        data["fire"] = this.fire;
        data["motion"] = this.motion;
        data["sound"] = this.sound;
        data["rfid"] = this.rfid;
        return data;
    }
}

export interface ISmartQuartierEventStatistic {
    gas?: number;
    fire?: number;
    motion?: number;
    sound?: number;
    rfid?: number;
}

export class VersionInfo implements IVersionInfo {
    name?: string;
    semVer?: string;
    informationalVersion?: string;

    constructor(data?: IVersionInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.semVer = _data["semVer"];
            this.informationalVersion = _data["informationalVersion"];
        }
    }

    static fromJS(data: any): VersionInfo {
        data = typeof data === 'object' ? data : {};
        let result = new VersionInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["semVer"] = this.semVer;
        data["informationalVersion"] = this.informationalVersion;
        return data;
    }
}

export interface IVersionInfo {
    name?: string;
    semVer?: string;
    informationalVersion?: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}