//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    getAbout(): Promise<VersionInfo> {
        let url_ = this.baseUrl + "/about";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAbout(_response);
        });
    }

    protected processGetAbout(response: Response): Promise<VersionInfo> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = VersionInfo.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VersionInfo>(null as any);
    }

    getHouses(): Promise<HouseSnapshot[]> {
        let url_ = this.baseUrl + "/api/houses";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetHouses(_response);
        });
    }

    protected processGetHouses(response: Response): Promise<HouseSnapshot[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HouseSnapshot.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HouseSnapshot[]>(null as any);
    }

    getHouse(buildingId: string): Promise<HouseSnapshot> {
        let url_ = this.baseUrl + "/api/houses/{buildingId}";
        if (buildingId === undefined || buildingId === null)
            throw new globalThis.Error("The parameter 'buildingId' must be defined.");
        url_ = url_.replace("{buildingId}", encodeURIComponent("" + buildingId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetHouse(_response);
        });
    }

    protected processGetHouse(response: Response): Promise<HouseSnapshot> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = HouseSnapshot.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HouseSnapshot>(null as any);
    }
}

export class VersionInfo implements IVersionInfo {
    name!: string;
    semVer!: string;
    informationalVersion!: string;

    constructor(data?: IVersionInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.semVer = _data["semVer"];
            this.informationalVersion = _data["informationalVersion"];
        }
    }

    static fromJS(data: any): VersionInfo {
        data = typeof data === 'object' ? data : {};
        let result = new VersionInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["semVer"] = this.semVer;
        data["informationalVersion"] = this.informationalVersion;
        return data;
    }
}

export interface IVersionInfo {
    name: string;
    semVer: string;
    informationalVersion: string;
}

export class HouseSnapshot implements IHouseSnapshot {
    buildingId?: string;
    owner?: string;
    coordinates?: HouseCoordinates;
    temperature?: string;
    brightness?: string;
    humidity?: string;
    gasLevel?: string;
    state?: HouseState;
    sensors?: HouseSensors;

    constructor(data?: IHouseSnapshot) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.buildingId = _data["buildingId"];
            this.owner = _data["owner"];
            this.coordinates = _data["coordinates"] ? HouseCoordinates.fromJS(_data["coordinates"]) : undefined as any;
            this.temperature = _data["temperature"];
            this.brightness = _data["brightness"];
            this.humidity = _data["humidity"];
            this.gasLevel = _data["gasLevel"];
            this.state = _data["state"] ? HouseState.fromJS(_data["state"]) : undefined as any;
            this.sensors = _data["sensors"] ? HouseSensors.fromJS(_data["sensors"]) : undefined as any;
        }
    }

    static fromJS(data: any): HouseSnapshot {
        data = typeof data === 'object' ? data : {};
        let result = new HouseSnapshot();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["buildingId"] = this.buildingId;
        data["owner"] = this.owner;
        data["coordinates"] = this.coordinates ? this.coordinates.toJSON() : undefined as any;
        data["temperature"] = this.temperature;
        data["brightness"] = this.brightness;
        data["humidity"] = this.humidity;
        data["gasLevel"] = this.gasLevel;
        data["state"] = this.state ? this.state.toJSON() : undefined as any;
        data["sensors"] = this.sensors ? this.sensors.toJSON() : undefined as any;
        return data;
    }
}

export interface IHouseSnapshot {
    buildingId?: string;
    owner?: string;
    coordinates?: HouseCoordinates;
    temperature?: string;
    brightness?: string;
    humidity?: string;
    gasLevel?: string;
    state?: HouseState;
    sensors?: HouseSensors;
}

export class HouseCoordinates implements IHouseCoordinates {
    x?: number;
    y?: number;

    constructor(data?: IHouseCoordinates) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.x = _data["x"];
            this.y = _data["y"];
        }
    }

    static fromJS(data: any): HouseCoordinates {
        data = typeof data === 'object' ? data : {};
        let result = new HouseCoordinates();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["x"] = this.x;
        data["y"] = this.y;
        return data;
    }
}

export interface IHouseCoordinates {
    x?: number;
    y?: number;
}

export class HouseState implements IHouseState {
    dangerKind?: string;
    endangerment?: string;

    constructor(data?: IHouseState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.dangerKind = _data["dangerKind"];
            this.endangerment = _data["endangerment"];
        }
    }

    static fromJS(data: any): HouseState {
        data = typeof data === 'object' ? data : {};
        let result = new HouseState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["dangerKind"] = this.dangerKind;
        data["endangerment"] = this.endangerment;
        return data;
    }
}

export interface IHouseState {
    dangerKind?: string;
    endangerment?: string;
}

export class HouseSensors implements IHouseSensors {
    isLightOn?: boolean;
    isDoorLocked?: boolean;
    isHeatingOn?: boolean;
    isAlarmOn?: boolean;
    lightIntensity?: number;
    heatingIntensity?: number;
    displayValue?: string;

    constructor(data?: IHouseSensors) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isLightOn = _data["isLightOn"];
            this.isDoorLocked = _data["isDoorLocked"];
            this.isHeatingOn = _data["isHeatingOn"];
            this.isAlarmOn = _data["isAlarmOn"];
            this.lightIntensity = _data["lightIntensity"];
            this.heatingIntensity = _data["heatingIntensity"];
            this.displayValue = _data["displayValue"];
        }
    }

    static fromJS(data: any): HouseSensors {
        data = typeof data === 'object' ? data : {};
        let result = new HouseSensors();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isLightOn"] = this.isLightOn;
        data["isDoorLocked"] = this.isDoorLocked;
        data["isHeatingOn"] = this.isHeatingOn;
        data["isAlarmOn"] = this.isAlarmOn;
        data["lightIntensity"] = this.lightIntensity;
        data["heatingIntensity"] = this.heatingIntensity;
        data["displayValue"] = this.displayValue;
        return data;
    }
}

export interface IHouseSensors {
    isLightOn?: boolean;
    isDoorLocked?: boolean;
    isHeatingOn?: boolean;
    isAlarmOn?: boolean;
    lightIntensity?: number;
    heatingIntensity?: number;
    displayValue?: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}