// Projekt:      SmartHome
// Firma:        ABB Technikerschule
// Autor:        Marco Bontognali
//
// Beschreibung: Konfiguration des SmartHomes
//               - SmartHome.conf wird im aktuellen Directory gesucht
//               - Zeilen beginnend mit // werden nicht gelesen
//               - Starten mit Kommandozeile: java -jar SmartHome.jar

// Ohne Angabe wird das SmartHome simuliert
//HARDWARE_ON = true

// Ohne Angabe wird der nächste freie COM-Port verwendet
// Windows:    COM[*]
// Mac, Linux: /dev/tty[*]
//COM_PORT = COM3

// Leerzeichen innerhalb der Bezeichnung sind nicht erlaubt. Maximal 64 Zeichen.
BUILDING_ID = Haus-1

// Wird der Wert ueberschritten erfolgt der Alarm
GAS_ALARM_VALUE = 100
FIRE_ALARM_VALUE = 800

// Zutrittskontrolle
RFID_CARD_USER = 000-000-000-000-001
RFID_KEY_USER  = 000-000-000-000-002

// Ohne Angabe erfolgt keine Registrierung beim TelecomServer
//TELECOM_SERVER_IP = localhost
//TELECOM_SERVER_IP = 192.168.x.y

// Nullpunkt: Smarthome vorne links Blickrichtung Whiteboard
X_COORDINATE = 0
Y_COORDINATE = 0

OWNER = Mike

// Beliebig viele ServiceProvider. Ohne Angabe erfolgt keine Registrierung.
SERVICE_PROVIDER = DataService; 127.0.0.1:11000
//SERVICE_PROVIDER = MobileApp; 127.0.0.1:12000
//SERVICE_PROVIDER = Firefighter; 127.0.0.1:14000
//SERVICE_PROVIDER = TestService; 127.0.0.1:8080
